'use client'

import { AppLayout, BreadcrumbGroup, HelpPanel, SideNavigation } from '@cloudscape-design/components';
import { Inter } from 'next/font/google';
import '@cloudscape-design/global-styles/index.css'
import 'dotenv/config';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <AppLayout
      breadcrumbs={
        <BreadcrumbGroup
          items={[
            { text: 'Home', href: '#' },
            { text: 'Create Job', href: '#' },
          ]}
        />
      }
      // navigationOpen={false}
      navigation={
        <SideNavigation
          header={{
            href: '#',
            text: 'Media Convert Tool',
          }}
          items={[{ type: 'link', text: `Create Job`, href: `#` }]}
        />
      }
      // toolsOpen={false}
      tools={<HelpPanel header={<h2>Overview</h2>}>Help content</HelpPanel>}
      content={children}
      // splitPanel={<SplitPanel header="Split panel header">Split panel content</SplitPanel>}
    />
    </body>
    </html>
  );
}
